### ISSUE TITLE
Add testcoverage in Codacy

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/terraform-provider-cobbler#44]
### Is your feature request related to a problem?

As a maintainer  
I want to be aware of untested code  
so that I can be aware of the risk to merge a PR.

### Provide a detailed description of the proposed feature

Collect the coverage reports that go test generated in a Codacy-supported format and upload them.

### Alternatives you've considered

None

### Additional information

The upload needs to happen on the `main` branch so we have the secrets available. We only needs to upload a single report from a single os and Golang version.

To upload we can use the following snippet:

```yml
      - name: Upload test coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.out
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: ${{ secrets.CODACY_ORGANIZATION_PROVIDER }}
          CODACY_USERNAME: ${{ secrets.CODACY_USERNAME }}
          CODACY_PROJECT_NAME: ${{ secrets.CODACY_PROJECT_NAME }}
```
